### ISSUE TITLE
websocket Error

### ISSUE THREAD

**Issue by jeganrajrajan** [rena2damas/remote-opencv-streaming-live-video#2]
when i used  to run the client.py file in client machine it gave below issue:
host : client machine ip 
port: 8089
    clientsocket.connect(('10.11.20.60',8089))
ConnectionRefusedError: [Errno 111] Connection refused
 

can you please help me to solve this issue. Thanks in advance.

**Comment by balajib363** [comment]
same issue!

**Comment by dfd19** [comment]
when you have run the server.py, you have open the browser (default localhost:5000 in my PC). then, you can run client.py 

(but it still has some problem (especially if you use python3), you have to convert StringIO to BytesIO in python3)

**Comment by balajib363** [comment]
@dfd19  I tried both in python2 and python3 issue we face is, not able to see any live stream after executing the client.py. But the machine will start consuming full power on execution and it also crashed the machine for me.

**Comment by rd3x** [comment]
Hi guys. Sorry for the late reply.
The connection refuse happens because you need to have the server running and access the endpoint in your browser. Only then the socket connection will be in place and you will stop receiving that error. I might make some improvements here so please provide feedback.

**Comment by rd3x** [comment]
Additional note, I made several improvements in the code that might be worth to try:

- got rid of unnecessary steps that improve the streaming connection providing a near fluente and real time streaming connection.
- code is python 3 compatible
- added requirements.txt for your python environments

Please reach out to me if you need further help. Any feedback is also appreciated and I am open to pull requests as well.
