### ISSUE TITLE
Provide The Code With Requirements.txt

### ISSUE THREAD

**Issue by asrulsibaoel** [rena2damas/remote-opencv-streaming-live-video#3]
Hi Man, really amazing repo! But I have a problem with the library you've used. I don't know the the libraries like socket, StringIO, etc. Please attach `requirements.txt` within your code. Thank you.

**Comment by rd3x** [comment]
Hi @asrulsibaoel sorry for the late reply. I made new code changes and I added the requirements.txt file to freeze the dependencies. Make sure to use some local python environment for your project. Feel free to reach out to me.
