### ISSUE TITLE
Python 3 compliant version ?

### ISSUE THREAD

**Issue by plfbvr** [rena2damas/remote-opencv-streaming-live-video#4]
I guess I already know the answer but is it a chance for this project to be adapted to python 3 ?

**Comment by Rockyzsu** [comment]
I modified some change to make it work for python3

https://github.com/Rockyzsu/CodePool/tree/master/remote-opencv-streaming-live-video

**Comment by rena2damas** [comment]
I have made a new update in the code. The code is now ready to be used with Python 3

**Comment by rd3x** [comment]
@plefebvre91 I have made a new update in the code. The code is now ready to be used with Python 3.
