### ISSUE TITLE
This script is using almost 40% of cpu while waiting for connection

### ISSUE THREAD

**Issue by TheFabbest** [rena2damas/remote-opencv-streaming-live-video#5]
While waiting for the client to connect, I get a 40% CPU usage, I think it has something to do with Flask. Since I have never used Flask, I wanted to ask if there were something that I could change in order to have a less cpu-intensive result.

Maybe putting something like this in server.py:

def gen():
  streamer = Streamer('localhost', 8080)
  streamer.start()

  while True:
    if streamer.streaming:
      yield (b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + streamer.get_jpeg() + b'\r\n\r\n')
    else: time.sleep(0.2)

**Comment by rd3x** [comment]
Hi @fabrizio03 you closed the issue, does it mean you were able to reduce the cpu activity ?

**Comment by TheFabbest** [comment]
Yes, I thought it was due to some wrong setting of the socket but I actually fixed it by editing server.py the way I did in the post, I didn't have the time to try before so I did it this morning and it worked.

**Comment by rd3x** [comment]
> Yes, I thought it was due to some wrong setting of the socket but I actually fixed it by editing server.py the way I did in the post, I didn't have the time to try before so I did it this morning and it worked.

Glad to hear that. But indeed, a sleep there reduces the number of iterations at that point so feel free to increase that value if necessary since it's only important once the streaming takes place.
